### PR TITLE
Update dependencies to AndroidX

### PR DESCRIPTION
**Pull request by cdeange**
Updates all dependencies from legacy the legacy support library to their AndroidX counterparts. This prevents the library from having to be Jetified to be used in consumers already supporting AndroidX.

### CODE REVIEW

**Comment by pforhan** [comment]
LGTM

**Comment by rjrjr** [comment]
Hard to imagine the travis build is worth anything. Running tests manually…

**Comment by pforhan** [comment]
yeah, a lot of our projects have broken travis builds now.  Should we make an effort to move to github actions?

**Comment by cdeange** [comment]
I managed to get travis to work here, just needed some minor changes. All green!

**Pull request merged**
